# Numpy 

* NumPy operations perform complex computations on entire arrays without the need for Python for loops.
* Fast vectorized array operations for data munging and cleaning, subsetting and filtering, transformation, and any other kinds of computations
* Common array algorithms like sorting, unique, and set operations
* Efficient descriptive statistics and aggregating/summarizing data
* Data alignment and relational data manipulations for merging and joining together heterogeneous datasets
* Expressing conditional logic as array expressions instead of loops with if-elif-else branches
* Group-wise data manipulations (aggregation, transformation, function application)

In [1]:
lst_num = [1,2,3,4]

In [2]:
import numpy as np

In [3]:
from numpy import arange

# Faster Computation

In [4]:
np_array = np.arange(1000000)
lst_num = list(range(1000000))

In [5]:
%%time 
for i in range(10): np_array = np_array*2

Wall time: 76.3 ms


In [6]:
%%time
for i in range(10): lst_num = [i*2 for i in lst_num]

Wall time: 2.88 s


# ndarray

In [7]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [8]:
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
arr2

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [9]:
# Do not use len to get length of numpy array
arr2.ndim

2

In [10]:
arr2.shape

(2, 5)

In [11]:
# Do not use type to get datatype of numpy array
arr2.dtype

dtype('int32')

<dl class="docutils">
<dt>ndarray.ndim</dt>
<dd>the number of axes (dimensions) of the array.</dd>
<dt>ndarray.shape</dt>
<dd>the dimensions of the array. This is a tuple of integers indicating
the size of the array in each dimension. For a matrix with <em>n</em> rows
and <em>m</em> columns, <code class="docutils literal notranslate"><span class="pre">shape</span></code> will be <code class="docutils literal notranslate"><span class="pre">(n,m)</span></code>. The length of the
<code class="docutils literal notranslate"><span class="pre">shape</span></code> tuple is therefore the number of axes, <code class="docutils literal notranslate"><span class="pre">ndim</span></code>.</dd>
<dt>ndarray.size</dt>
<dd>the total number of elements of the array. This is equal to the
product of the elements of <code class="docutils literal notranslate"><span class="pre">shape</span></code>.</dd>
<dt>ndarray.dtype</dt>
<dd>an object describing the type of the elements in the array. One can
create or specify dtype’s using standard Python types. Additionally
NumPy provides types of its own. numpy.int32, numpy.int16, and
numpy.float64 are some examples.</dd>
<dt>ndarray.itemsize</dt>
<dd>the size in bytes of each element of the array. For example, an
array of elements of type <code class="docutils literal notranslate"><span class="pre">float64</span></code> has <code class="docutils literal notranslate"><span class="pre">itemsize</span></code> 8 (=64/8),
while one of type <code class="docutils literal notranslate"><span class="pre">complex32</span></code> has <code class="docutils literal notranslate"><span class="pre">itemsize</span></code> 4 (=32/8). It is
equivalent to <code class="docutils literal notranslate"><span class="pre">ndarray.dtype.itemsize</span></code>.</dd>
<dt>ndarray.data</dt>
<dd>the buffer containing the actual elements of the array. Normally, we
won’t need to use this attribute because we will access the elements
in an array using indexing facilities.</dd>
</dl>

In [12]:
arr2.shape

(2, 5)

## Data type while creation

In [13]:
arr3 = np.array([1,2,3,4], dtype = float)
arr3.dtype

dtype('float64')

In [14]:
arr3

array([1., 2., 3., 4.])

## Array creation with function

In [15]:
np.zeros((4,5),dtype='int64')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [16]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
np.arange(5,50,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [18]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [19]:
np.random.randint(1,10,size = (3,2))

array([[9, 7],
       [2, 1],
       [2, 1]])

In [25]:
np.random?

In [24]:
#np.arange(5,65,5)
np.arange(5,65,5).reshape(4,3)

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [50, 55, 60]])

# Basic Operations

In [26]:
a = np.arange(2,10,2)
b = np.arange(1,9,2)
a,b

(array([2, 4, 6, 8]), array([1, 3, 5, 7]))

In [27]:
a+b

array([ 3,  7, 11, 15])

In [28]:
a*b

array([ 2, 12, 30, 56])

In [29]:
arow1 = np.arange(1,5,2)
arow2 = np.arange(2,6,2)
A = np.array((arow1,arow2))
A

array([[1, 3],
       [2, 4]])

In [30]:
brow1 = np.arange(0,3,2)
brow2 = np.arange(1,4,2)
B = np.array((brow1,brow2))
B

array([[0, 2],
       [1, 3]])

In [31]:
A*B

array([[ 0,  6],
       [ 2, 12]])

In [32]:
A @ B

array([[ 3, 11],
       [ 4, 16]])

In [33]:
A .dot(B)

array([[ 3, 11],
       [ 4, 16]])

## Vector Operations 


In [34]:
X = np.arange(5,65,5).reshape(4,3)
X

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [50, 55, 60]])

In [35]:
Y = np.arange(3,39,3).reshape(4,3)
Y

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27],
       [30, 33, 36]])

In [36]:
Z = X + Y
Z

array([[ 8, 16, 24],
       [32, 40, 48],
       [56, 64, 72],
       [80, 88, 96]])

In [37]:
Z += X
Z

array([[ 13,  26,  39],
       [ 52,  65,  78],
       [ 91, 104, 117],
       [130, 143, 156]])

* axis = 0 columnwise vectors
* axis = 1 rowwise vectors

<html>
        <img src ="aggregation_row.png" />
    </html>
    

In [39]:
X

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [50, 55, 60]])

In [38]:
X.min(axis = 0),X.min(axis=1),X.min()

(array([ 5, 10, 15]), array([ 5, 20, 35, 50]), 5)

In [40]:
X.sum(axis = 1)

array([ 30,  75, 120, 165])

In [41]:
X.cumsum(axis = 1)

array([[  5,  15,  30],
       [ 20,  45,  75],
       [ 35,  75, 120],
       [ 50, 105, 165]], dtype=int32)

In [42]:
X

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [50, 55, 60]])

In [45]:
X.argmax(axis = 1), X.argmax(axis=0)

(array([2, 2, 2, 2], dtype=int64), array([3, 3, 3], dtype=int64))

In [44]:
np.where(X <25,0,X)

array([[ 0,  0,  0],
       [ 0, 25, 30],
       [35, 40, 45],
       [50, 55, 60]])

# Indexing , Slicing and Iterating

<html>
        <img src = "np_indexing.png" />
    </html>

## Indexing using Boolean values

In [46]:
X,Y

(array([[ 5, 10, 15],
        [20, 25, 30],
        [35, 40, 45],
        [50, 55, 60]]),
 array([[ 3,  6,  9],
        [12, 15, 18],
        [21, 24, 27],
        [30, 33, 36]]))

In [47]:
X[:3],X[1:]

(array([[ 5, 10, 15],
        [20, 25, 30],
        [35, 40, 45]]),
 array([[20, 25, 30],
        [35, 40, 45],
        [50, 55, 60]]))

In [48]:
X[:,:2],X[:,1:]

(array([[ 5, 10],
        [20, 25],
        [35, 40],
        [50, 55]]),
 array([[10, 15],
        [25, 30],
        [40, 45],
        [55, 60]]))

In [49]:
mask_row = np.array([True,False,True,False])
mask_col = np.array([True, False,True])

In [50]:
X[mask_row,:],X[:,mask_col]

(array([[ 5, 10, 15],
        [35, 40, 45]]),
 array([[ 5, 15],
        [20, 30],
        [35, 45],
        [50, 60]]))

In [52]:
X

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [50, 55, 60]])

In [51]:
X[X>15],X[X%2==0]

(array([20, 25, 30, 35, 40, 45, 50, 55, 60]), array([10, 20, 30, 40, 50, 60]))

# Broadcasting

In [53]:
a = np.array([1,2]).reshape(2,1)
a

array([[1],
       [2]])

In [54]:
a*1.6

array([[1.6],
       [3.2]])

<html>
    <img src="broadcasting.png" />
    </html>

In [55]:
X

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [50, 55, 60]])

In [56]:
X + np.array([1,1,1])

array([[ 6, 11, 16],
       [21, 26, 31],
       [36, 41, 46],
       [51, 56, 61]])

In [59]:
X * np.array([1,2,1])

array([[  5,  20,  15],
       [ 20,  50,  30],
       [ 35,  80,  45],
       [ 50, 110,  60]])

<html>
    <img src = "broadcasting_2.png" />
    </html>

# Mathematical Formulae

Distance Formula

$d = \sqrt{{(x_2 - x_1)}^2 + {(y_2 - y_1)}^2}$

In [60]:
x = np.array([0,0]).reshape(2,1)
y = np.array([0,1]).reshape(2,1)

In [61]:
x,y

(array([[0],
        [0]]),
 array([[0],
        [1]]))

In [62]:
np.sqrt(np.sum(np.square(x-y)))

1.0

<div class="section" id="functions-and-methods-overview">
<h3>Functions and Methods Overview<a class="headerlink" href="#functions-and-methods-overview" title="Permalink to this headline">¶</a></h3>
<p>Here is a list of some useful NumPy functions and methods names
ordered in categories. See <a class="reference internal" href="../reference/routines.html#routines"><span class="std std-ref">Routines</span></a> for the full list.</p>
<dl class="docutils">
<dt>Array Creation</dt>
<dd><a class="reference internal" href="../reference/generated/numpy.arange.html#numpy.arange" title="numpy.arange"><code class="xref py py-obj docutils literal notranslate"><span class="pre">arange</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.array.html#numpy.array" title="numpy.array"><code class="xref py py-obj docutils literal notranslate"><span class="pre">array</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.copy.html#numpy.copy" title="numpy.copy"><code class="xref py py-obj docutils literal notranslate"><span class="pre">copy</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.empty.html#numpy.empty" title="numpy.empty"><code class="xref py py-obj docutils literal notranslate"><span class="pre">empty</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.empty_like.html#numpy.empty_like" title="numpy.empty_like"><code class="xref py py-obj docutils literal notranslate"><span class="pre">empty_like</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.eye.html#numpy.eye" title="numpy.eye"><code class="xref py py-obj docutils literal notranslate"><span class="pre">eye</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.fromfile.html#numpy.fromfile" title="numpy.fromfile"><code class="xref py py-obj docutils literal notranslate"><span class="pre">fromfile</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.fromfunction.html#numpy.fromfunction" title="numpy.fromfunction"><code class="xref py py-obj docutils literal notranslate"><span class="pre">fromfunction</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.identity.html#numpy.identity" title="numpy.identity"><code class="xref py py-obj docutils literal notranslate"><span class="pre">identity</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.linspace.html#numpy.linspace" title="numpy.linspace"><code class="xref py py-obj docutils literal notranslate"><span class="pre">linspace</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.logspace.html#numpy.logspace" title="numpy.logspace"><code class="xref py py-obj docutils literal notranslate"><span class="pre">logspace</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.mgrid.html#numpy.mgrid" title="numpy.mgrid"><code class="xref py py-obj docutils literal notranslate"><span class="pre">mgrid</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.ogrid.html#numpy.ogrid" title="numpy.ogrid"><code class="xref py py-obj docutils literal notranslate"><span class="pre">ogrid</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.ones.html#numpy.ones" title="numpy.ones"><code class="xref py py-obj docutils literal notranslate"><span class="pre">ones</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.ones_like.html#numpy.ones_like" title="numpy.ones_like"><code class="xref py py-obj docutils literal notranslate"><span class="pre">ones_like</span></code></a>,
<em class="xref py py-obj">r</em>,
<a class="reference internal" href="../reference/generated/numpy.zeros.html#numpy.zeros" title="numpy.zeros"><code class="xref py py-obj docutils literal notranslate"><span class="pre">zeros</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.zeros_like.html#numpy.zeros_like" title="numpy.zeros_like"><code class="xref py py-obj docutils literal notranslate"><span class="pre">zeros_like</span></code></a></dd>
<dt>Conversions</dt>
<dd><a class="reference internal" href="../reference/generated/numpy.ndarray.astype.html#numpy.ndarray.astype" title="numpy.ndarray.astype"><code class="xref py py-obj docutils literal notranslate"><span class="pre">ndarray.astype</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.atleast_1d.html#numpy.atleast_1d" title="numpy.atleast_1d"><code class="xref py py-obj docutils literal notranslate"><span class="pre">atleast_1d</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.atleast_2d.html#numpy.atleast_2d" title="numpy.atleast_2d"><code class="xref py py-obj docutils literal notranslate"><span class="pre">atleast_2d</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.atleast_3d.html#numpy.atleast_3d" title="numpy.atleast_3d"><code class="xref py py-obj docutils literal notranslate"><span class="pre">atleast_3d</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.mat.html#numpy.mat" title="numpy.mat"><code class="xref py py-obj docutils literal notranslate"><span class="pre">mat</span></code></a></dd>
<dt>Manipulations</dt>
<dd><a class="reference internal" href="../reference/generated/numpy.array_split.html#numpy.array_split" title="numpy.array_split"><code class="xref py py-obj docutils literal notranslate"><span class="pre">array_split</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.column_stack.html#numpy.column_stack" title="numpy.column_stack"><code class="xref py py-obj docutils literal notranslate"><span class="pre">column_stack</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.concatenate.html#numpy.concatenate" title="numpy.concatenate"><code class="xref py py-obj docutils literal notranslate"><span class="pre">concatenate</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.diagonal.html#numpy.diagonal" title="numpy.diagonal"><code class="xref py py-obj docutils literal notranslate"><span class="pre">diagonal</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.dsplit.html#numpy.dsplit" title="numpy.dsplit"><code class="xref py py-obj docutils literal notranslate"><span class="pre">dsplit</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.dstack.html#numpy.dstack" title="numpy.dstack"><code class="xref py py-obj docutils literal notranslate"><span class="pre">dstack</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.hsplit.html#numpy.hsplit" title="numpy.hsplit"><code class="xref py py-obj docutils literal notranslate"><span class="pre">hsplit</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.hstack.html#numpy.hstack" title="numpy.hstack"><code class="xref py py-obj docutils literal notranslate"><span class="pre">hstack</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.ndarray.item.html#numpy.ndarray.item" title="numpy.ndarray.item"><code class="xref py py-obj docutils literal notranslate"><span class="pre">ndarray.item</span></code></a>,
<a class="reference internal" href="../reference/constants.html#numpy.newaxis" title="numpy.newaxis"><code class="xref py py-obj docutils literal notranslate"><span class="pre">newaxis</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.ravel.html#numpy.ravel" title="numpy.ravel"><code class="xref py py-obj docutils literal notranslate"><span class="pre">ravel</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.repeat.html#numpy.repeat" title="numpy.repeat"><code class="xref py py-obj docutils literal notranslate"><span class="pre">repeat</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.reshape.html#numpy.reshape" title="numpy.reshape"><code class="xref py py-obj docutils literal notranslate"><span class="pre">reshape</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.resize.html#numpy.resize" title="numpy.resize"><code class="xref py py-obj docutils literal notranslate"><span class="pre">resize</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.squeeze.html#numpy.squeeze" title="numpy.squeeze"><code class="xref py py-obj docutils literal notranslate"><span class="pre">squeeze</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.swapaxes.html#numpy.swapaxes" title="numpy.swapaxes"><code class="xref py py-obj docutils literal notranslate"><span class="pre">swapaxes</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.take.html#numpy.take" title="numpy.take"><code class="xref py py-obj docutils literal notranslate"><span class="pre">take</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.transpose.html#numpy.transpose" title="numpy.transpose"><code class="xref py py-obj docutils literal notranslate"><span class="pre">transpose</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.vsplit.html#numpy.vsplit" title="numpy.vsplit"><code class="xref py py-obj docutils literal notranslate"><span class="pre">vsplit</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.vstack.html#numpy.vstack" title="numpy.vstack"><code class="xref py py-obj docutils literal notranslate"><span class="pre">vstack</span></code></a></dd>
<dt>Questions</dt>
<dd><a class="reference internal" href="../reference/generated/numpy.all.html#numpy.all" title="numpy.all"><code class="xref py py-obj docutils literal notranslate"><span class="pre">all</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.any.html#numpy.any" title="numpy.any"><code class="xref py py-obj docutils literal notranslate"><span class="pre">any</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.nonzero.html#numpy.nonzero" title="numpy.nonzero"><code class="xref py py-obj docutils literal notranslate"><span class="pre">nonzero</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.where.html#numpy.where" title="numpy.where"><code class="xref py py-obj docutils literal notranslate"><span class="pre">where</span></code></a></dd>
<dt>Ordering</dt>
<dd><a class="reference internal" href="../reference/generated/numpy.argmax.html#numpy.argmax" title="numpy.argmax"><code class="xref py py-obj docutils literal notranslate"><span class="pre">argmax</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.argmin.html#numpy.argmin" title="numpy.argmin"><code class="xref py py-obj docutils literal notranslate"><span class="pre">argmin</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.argsort.html#numpy.argsort" title="numpy.argsort"><code class="xref py py-obj docutils literal notranslate"><span class="pre">argsort</span></code></a>,
<a class="reference external" href="https://docs.python.org/dev/library/functions.html#max" title="(in Python v3.9)"><code class="xref py py-obj docutils literal notranslate"><span class="pre">max</span></code></a>,
<a class="reference external" href="https://docs.python.org/dev/library/functions.html#min" title="(in Python v3.9)"><code class="xref py py-obj docutils literal notranslate"><span class="pre">min</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.ptp.html#numpy.ptp" title="numpy.ptp"><code class="xref py py-obj docutils literal notranslate"><span class="pre">ptp</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.searchsorted.html#numpy.searchsorted" title="numpy.searchsorted"><code class="xref py py-obj docutils literal notranslate"><span class="pre">searchsorted</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.sort.html#numpy.sort" title="numpy.sort"><code class="xref py py-obj docutils literal notranslate"><span class="pre">sort</span></code></a></dd>
<dt>Operations</dt>
<dd><a class="reference internal" href="../reference/generated/numpy.choose.html#numpy.choose" title="numpy.choose"><code class="xref py py-obj docutils literal notranslate"><span class="pre">choose</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.compress.html#numpy.compress" title="numpy.compress"><code class="xref py py-obj docutils literal notranslate"><span class="pre">compress</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.cumprod.html#numpy.cumprod" title="numpy.cumprod"><code class="xref py py-obj docutils literal notranslate"><span class="pre">cumprod</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.cumsum.html#numpy.cumsum" title="numpy.cumsum"><code class="xref py py-obj docutils literal notranslate"><span class="pre">cumsum</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.inner.html#numpy.inner" title="numpy.inner"><code class="xref py py-obj docutils literal notranslate"><span class="pre">inner</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.ndarray.fill.html#numpy.ndarray.fill" title="numpy.ndarray.fill"><code class="xref py py-obj docutils literal notranslate"><span class="pre">ndarray.fill</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.imag.html#numpy.imag" title="numpy.imag"><code class="xref py py-obj docutils literal notranslate"><span class="pre">imag</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.prod.html#numpy.prod" title="numpy.prod"><code class="xref py py-obj docutils literal notranslate"><span class="pre">prod</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.put.html#numpy.put" title="numpy.put"><code class="xref py py-obj docutils literal notranslate"><span class="pre">put</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.putmask.html#numpy.putmask" title="numpy.putmask"><code class="xref py py-obj docutils literal notranslate"><span class="pre">putmask</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.real.html#numpy.real" title="numpy.real"><code class="xref py py-obj docutils literal notranslate"><span class="pre">real</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.sum.html#numpy.sum" title="numpy.sum"><code class="xref py py-obj docutils literal notranslate"><span class="pre">sum</span></code></a></dd>
<dt>Basic Statistics</dt>
<dd><a class="reference internal" href="../reference/generated/numpy.cov.html#numpy.cov" title="numpy.cov"><code class="xref py py-obj docutils literal notranslate"><span class="pre">cov</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.mean.html#numpy.mean" title="numpy.mean"><code class="xref py py-obj docutils literal notranslate"><span class="pre">mean</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.std.html#numpy.std" title="numpy.std"><code class="xref py py-obj docutils literal notranslate"><span class="pre">std</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.var.html#numpy.var" title="numpy.var"><code class="xref py py-obj docutils literal notranslate"><span class="pre">var</span></code></a></dd>
<dt>Basic Linear Algebra</dt>
<dd><a class="reference internal" href="../reference/generated/numpy.cross.html#numpy.cross" title="numpy.cross"><code class="xref py py-obj docutils literal notranslate"><span class="pre">cross</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.dot.html#numpy.dot" title="numpy.dot"><code class="xref py py-obj docutils literal notranslate"><span class="pre">dot</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.outer.html#numpy.outer" title="numpy.outer"><code class="xref py py-obj docutils literal notranslate"><span class="pre">outer</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.linalg.svd.html#numpy.linalg.svd" title="numpy.linalg.svd"><code class="xref py py-obj docutils literal notranslate"><span class="pre">linalg.svd</span></code></a>,
<a class="reference internal" href="../reference/generated/numpy.vdot.html#numpy.vdot" title="numpy.vdot"><code class="xref py py-obj docutils literal notranslate"><span class="pre">vdot</span></code></a></dd>
</dl>
</div>
</div>